apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-app
  namespace: "default"
  labels:
    app: dapr-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dapr-app
  template:
    metadata:
      labels:
        app: dapr-app
        azure.workload.identity/use: "true"
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "dapr-app"
        dapr.io/app-port: "8080"
        dapr.io/log-level: "debug"
    spec:
      serviceAccountName: svc-dappr
      containers:
        - name: dapr-app
          image: docker.io/mickstevenson888/aksdappr:0.0.5
          ports:
            - containerPort: 8080
          env:
            - name: DAPR_HTTP_PORT
              value: "3500"
